FROM node:16.0.0-alpine as build
WORKDIR /myapp

COPY . /myapp
RUN yarn install
RUN yarn build

FROM nginx:alpine
COPY --from=build /myapp/build /var/www
COPY ./nginx /etc/nginx/conf.d/

WORKDIR /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
