default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db
  
development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test
  strict: false

production:
  <<: *default
  database: <%= Rails.application.credentials.DB[:db_database] %>
  username: <%= Rails.application.credentials.DB[:db_username] %>
  password: <%= Rails.application.credentials.DB[:db_password] %>
  host: <%= Rails.application.credentials.DB[:db_host] %>
